#!/usr/bin/env bash
#
# End-to-end smoke test for the upload -> transcode -> HLS pipeline.
#
# Exercises the whole path against the running compose stack:
#   1. validation rejects bad requests
#   2. mint a presigned upload target, PUT real bytes straight to object storage
#   3. confirm the upload, which publishes VideoUploadedEvent
#   4. transcoder-service consumes it and publishes video.ready
#   5. assert the row reached READY with a real, correct ladder
#   6. assert every playlist and segment is actually fetchable
#   7. assert consumer idempotency under duplicate and out-of-order events
#
# Exits non-zero on the first failed assertion, dumping both service logs so a failure is
# diagnosable without a second command.

set -euo pipefail

# Through the gateway, not straight to video-service. The service now rejects anything without
# the internal gateway secret, so calling it directly is both unsupported and impossible - which
# is the point. Registering a throwaway user here also means the E2E exercises the same identity
# path the iOS client will.
VIDEO_URL="${VIDEO_URL:-http://localhost:8080}"
S3_PUBLIC="${S3_PUBLIC:-http://localhost:4566}"
RABBIT_API="${RABBIT_API:-http://localhost:15672}"
USER_ID="${USER_ID:-e2e-test-user}"
DURATION="${DURATION:-8}"
STAMP="$(date +%s)"

RED=$'\033[31m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; RESET=$'\033[0m'
step() { printf '%s==>%s %s\n' "$YELLOW" "$RESET" "$1"; }
pass() { printf '%s  ok%s %s\n' "$GREEN" "$RESET" "$1"; }
fail() { printf '%sFAIL%s %s\n' "$RED" "$RESET" "$1"; exit 1; }

WORKDIR="$(mktemp -d)"
cleanup() { rm -rf "$WORKDIR"; }
dump_logs() {
    echo
    echo "--------- transcoder-service ---------"; docker compose logs --tail 40 transcoder 2>&1 | sed 's/^/  /'
    echo "--------- video-service ------------"; docker compose logs --tail 40 video-service 2>&1 | sed 's/^/  /'
}
trap 'dump_logs' ERR
trap cleanup EXIT

jq_get() { python3 -c "import json,sys;print(json.load(sys.stdin)$1)"; }

# Presigns are generated with the in-container endpoint, which the host cannot resolve.
# Local-networking artifact only: against real S3 the presign is a genuine AWS URL.
# Reads the URL on stdin, so it composes in a pipeline.
to_public() { sed "s|http://localstack:4566|${S3_PUBLIC}|"; }

# Uses auth_curl, so the video is attributed to the registered user rather than to whatever
# identity the caller asserted.
create_video() {
    local title="$1"
    auth_curl -X POST "$VIDEO_URL/api/v1/videos" \
        -H 'Content-Type: application/json' \
        -d "{\"title\":\"$title\",\"description\":\"generated by scripts/e2e-pipeline-test.sh\",\"contentType\":\"video/mp4\"}"
}

rabbit_publish() {
    local routing_key="$1" payload="$2"
    python3 - "$routing_key" "$payload" <<'PY' > "$WORKDIR/publish.json"
import json, sys
print(json.dumps({
    "properties": {"content_type": "application/json"},
    "routing_key": sys.argv[1],
    "payload": sys.argv[2],
    "payload_encoding": "string",
}))
PY
    curl -s -o /dev/null -w '%{http_code}' -u guest:guest \
        -H 'Content-Type: application/json' \
        -X POST "$RABBIT_API/api/exchanges/%2F/video.exchange/publish" \
        --data-binary "@$WORKDIR/publish.json"
}

# ------------------------------------------------------- authenticated caller
step "Registering a throwaway user to get an access token"
AUTH=$(curl -s -X POST "$VIDEO_URL/api/v1/auth/register" -H 'Content-Type: application/json' \
    -d "{\"username\":\"pipe$STAMP\",\"email\":\"pipe$STAMP@example.com\",\"password\":\"correct-horse-battery-staple\"}")
TOKEN=$(printf '%s' "$AUTH" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("token",""))')
[ -n "$TOKEN" ] || fail "could not register an E2E user: $AUTH"
pass "token acquired"

auth_curl() { curl -s -H "Authorization: Bearer $TOKEN" "$@"; }

# A second account, for the ownership check. A forged X-User-Id would also be rejected, but that
# would prove the header is ignored rather than that ownership is enforced.
OTHER_AUTH=$(curl -s -X POST "$VIDEO_URL/api/v1/auth/register" -H 'Content-Type: application/json' \
    -d "{\"username\":\"other$STAMP\",\"email\":\"other$STAMP@example.com\",\"password\":\"correct-horse-battery-staple\"}")
OTHER_TOKEN=$(printf '%s' "$OTHER_AUTH" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("token",""))')
[ -n "$OTHER_TOKEN" ] || fail "could not register the second E2E user"

# ------------------------------------------------------------------ input clip
step "Generating a ${DURATION}s 1080x1920 test clip"
SOURCE="$WORKDIR/source.mp4"
ffmpeg -y -nostdin -hide_banner -loglevel error \
    -f lavfi -i "testsrc2=size=1080x1920:rate=30:duration=${DURATION}" \
    -f lavfi -i "sine=frequency=440:duration=${DURATION}" \
    -c:v libx264 -preset ultrafast -pix_fmt yuv420p -c:a aac -shortest "$SOURCE"
[ -s "$SOURCE" ] || fail "could not generate a test clip"
pass "clip is $(du -h "$SOURCE" | cut -f1)"

# ------------------------------------------------------------- input validation
step "Rejects a non-video content type"
CODE=$(auth_curl -o /dev/null -w '%{http_code}' -X POST "$VIDEO_URL/api/v1/videos" \
    -H 'Content-Type: application/json' \
    -d '{"title":"not a video","description":"x","contentType":"text/html"}')
[ "$CODE" = "400" ] || fail "expected 400 for contentType=text/html, got $CODE"
pass "400"

step "Rejects an over-long title"
LONG_TITLE=$(printf 'x%.0s' $(seq 1 300))
CODE=$(auth_curl -o /dev/null -w '%{http_code}' -X POST "$VIDEO_URL/api/v1/videos" \
    -H 'Content-Type: application/json' \
    -d "{\"title\":\"$LONG_TITLE\",\"contentType\":\"video/mp4\"}")
[ "$CODE" = "400" ] || fail "expected 400 for a 300-char title, got $CODE"
pass "400"

# ------------------------------------------------------------- upload the happy path
step "Requesting a presigned upload target"
CREATE_RESPONSE=$(create_video "e2e test clip")
VIDEO_ID=$(printf '%s' "$CREATE_RESPONSE" | jq_get "['videoId']")
UPLOAD_URL=$(printf '%s' "$CREATE_RESPONSE" | jq_get "['uploadUrl']" | to_public)
MAX_BYTES=$(printf '%s' "$CREATE_RESPONSE" | jq_get "['maxBytes']")
MAX_DURATION=$(printf '%s' "$CREATE_RESPONSE" | jq_get "['maxDurationSeconds']")
[ -n "$VIDEO_ID" ] && [ -n "$UPLOAD_URL" ] || fail "no videoId/uploadUrl in: $CREATE_RESPONSE"
pass "videoId=$VIDEO_ID maxBytes=$MAX_BYTES maxDuration=${MAX_DURATION}s"

step "The row starts in UPLOADING, never READY"
STATUS=$(auth_curl "$VIDEO_URL/api/v1/videos/$VIDEO_ID" | jq_get "['videoStatus']")
[ "$STATUS" = "UPLOADING" ] || fail "expected UPLOADING, got $STATUS"
pass "UPLOADING"

step "Uploading the clip straight to object storage"
CODE=$(curl -s -o /dev/null -w '%{http_code}' -X PUT "$UPLOAD_URL" \
    -H 'Content-Type: video/mp4' --data-binary "@$SOURCE")
case "$CODE" in 200|204) pass "$CODE" ;; *) fail "upload failed with $CODE" ;; esac

step "Completing the upload returns 202 and PROCESSING"
CODE=$(auth_curl -o "$WORKDIR/complete.json" -w '%{http_code}' \
    -X POST "$VIDEO_URL/api/v1/videos/$VIDEO_ID/complete")
[ "$CODE" = "202" ] || fail "expected 202, got $CODE: $(cat "$WORKDIR/complete.json")"
STATUS=$(jq_get "['videoStatus']" < "$WORKDIR/complete.json")
[ "$STATUS" = "PROCESSING" ] || fail "expected PROCESSING, got $STATUS"
pass "202 / PROCESSING"

# -------------------------------------------------------- /complete integrity gate
step "/complete rejects a video whose object was never uploaded"
BOGUS=$(create_video "never uploaded" | jq_get "['videoId']")
CODE=$(auth_curl -o "$WORKDIR/problem.json" -w '%{http_code}' \
    -X POST "$VIDEO_URL/api/v1/videos/$BOGUS/complete")
[ "$CODE" = "409" ] || fail "expected 409 for a missing object, got $CODE"
PROBLEM_CODE=$(jq_get ".get('code','')" < "$WORKDIR/problem.json")
[ "$PROBLEM_CODE" = "upload-missing" ] || fail "expected UPLOAD_MISSING, got '$PROBLEM_CODE'"
pass "409 / UPLOAD_MISSING"

# ------------------------------------------------------------------ wait for READY
step "Waiting for transcoder-service to publish video.ready (up to 180s)"
DEADLINE=$((SECONDS + 180))
STATUS=UNKNOWN
while [ $SECONDS -lt $DEADLINE ]; do
    BODY=$(auth_curl "$VIDEO_URL/api/v1/videos/$VIDEO_ID")
    STATUS=$(printf '%s' "$BODY" | jq_get "['videoStatus']")
    [ "$STATUS" = "READY" ] || [ "$STATUS" = "FAILED" ] && break
    sleep 3
done
if [ "$STATUS" = "FAILED" ]; then
    fail "transcode failed: $(printf '%s' "$BODY" | jq_get ".get('failureReason')") - $(printf '%s' "$BODY" | jq_get ".get('failureMessage')")"
fi
[ "$STATUS" = "READY" ] || fail "timed out waiting for READY (last status: $STATUS)"
printf '%s' "$BODY" > "$WORKDIR/ready.json"
pass "READY"

# ------------------------------------------------------------------ ladder metadata
step "Ladder metadata is correct"
python3 - "$WORKDIR/ready.json" <<'PY'
import json, sys
v = json.load(open(sys.argv[1]))
print(f"    playbackUrl : {v['playbackUrl']}")
print(f"    posterUrl   : {v['posterUrl']}")
print(f"    spriteUrl   : {v['thumbnailSpriteUrl']}")
print(f"    duration    : {v['durationSeconds']}s   geometry: {v['width']}x{v['height']}")
print(f"    sourceBytes : {v['sourceBytes']}")
print("    renditions  : " + ", ".join(
    f"{r['name']}={r['width']}x{r['height']}@{r['videoKbps']}k" for r in v['renditions']))

assert v['playbackUrl'], "playbackUrl missing"
assert v['posterUrl'], "posterUrl missing"
assert v['durationSeconds'] and v['durationSeconds'] > 0, "durationSeconds not set"
assert (v['width'], v['height']) == (1080, 1920), f"geometry {v['width']}x{v['height']}"
assert len(v['renditions']) == 6, f"expected 6 renditions, got {len(v['renditions'])}"
names = [r['name'] for r in v['renditions']]
assert names == sorted(names), f"renditions not highest-first: {names}"
# Every rung must be exact 9:16, or the CDN-cached ladder will have inconsistent geometry.
for r in v['renditions']:
    assert abs(r['width'] / r['height'] - 9 / 16) < 0.01, f"{r['name']} is not 9:16"
PY
pass "6 rungs, 9:16 throughout, highest first"

# ------------------------------------------------------------- fetch the real HLS
step "Fetching master.m3u8 from object storage"
HOST_MANIFEST=$(jq_get "['playbackUrl']" < "$WORKDIR/ready.json" | to_public)
curl -sf "$HOST_MANIFEST" -o "$WORKDIR/master.m3u8" || fail "could not fetch $HOST_MANIFEST"
grep -q '#EXTM3U' "$WORKDIR/master.m3u8" || fail "master.m3u8 is not a valid playlist"
VARIANTS=$(grep -c '#EXT-X-STREAM-INF' "$WORKDIR/master.m3u8")
[ "$VARIANTS" = "6" ] || fail "expected 6 variants in master, found $VARIANTS"
pass "master.m3u8 lists 6 variants"

step "Every variant playlist and its segments are fetchable"
BASE=$(dirname "$HOST_MANIFEST")
for V in v0 v1 v2 v3 v4 v5; do
    curl -sf "$BASE/$V/index.m3u8" -o "$WORKDIR/$V.m3u8" || fail "could not fetch $V/index.m3u8"
    grep -q '#EXT-X-PLAYLIST-TYPE:VOD' "$WORKDIR/$V.m3u8" || fail "$V is not a VOD playlist"
    grep -q '#EXT-X-INDEPENDENT-SEGMENTS' "$WORKDIR/$V.m3u8" || fail "$V lacks INDEPENDENT-SEGMENTS"
    # Every segment, not just the first: a truncated ladder is the failure mode that matters.
    while read -r SEG; do
        [ -n "$SEG" ] || continue
        curl -sf "$BASE/$V/$SEG" -o /dev/null || fail "missing segment $V/$SEG"
    done < <(grep -v '^#' "$WORKDIR/$V.m3u8")
    COUNT=$(grep -c -v '^#' "$WORKDIR/$V.m3u8")
    printf '    %s: %d segment(s), all fetchable\n' "$V" "$COUNT"
done
pass "all 6 renditions complete"

step "Poster and sprite sheet exist"
for KEY in posterUrl thumbnailSpriteUrl; do
    URL=$(jq_get "['$KEY']" < "$WORKDIR/ready.json" | to_public)
    curl -sf "$URL" -o "$WORKDIR/$KEY.jpg" || fail "$KEY not fetchable"
    printf '    %-20s %s\n' "$KEY" "$(du -h "$WORKDIR/$KEY.jpg" | cut -f1)"
done
pass "artwork present"

# ------------------------------------------------------ cover-frame selection
step "Selecting a cover frame from the sprite sheet"
auth_curl -sf -X PUT "$VIDEO_URL/api/v1/videos/$VIDEO_ID/thumbnail" \
    -H 'Content-Type: application/json' \
    -d '{"tileIndex":7}' -o "$WORKDIR/thumb.json" || fail "thumbnail selection rejected"
GOT=$(jq_get "['thumbnailTileIndex']" < "$WORKDIR/thumb.json")
[ "$GOT" = "7" ] || fail "expected thumbnailTileIndex=7, got $GOT"
pass "thumbnailTileIndex=7"

step "A non-owner cannot change the cover"
CODE=$(curl -s -o /dev/null -w '%{http_code}' -X PUT "$VIDEO_URL/api/v1/videos/$VIDEO_ID/thumbnail" \
    -H 'Content-Type: application/json' -H "Authorization: Bearer $OTHER_TOKEN" -d '{"tileIndex":1}')
[ "$CODE" = "403" ] || fail "expected 403 for a non-owner, got $CODE"
pass "403"

# ------------------------------------------------------------- idempotency checks
step "A duplicate video.ready is ignored rather than re-applied"
# Carries an empty rendition list and absurd values on purpose. If the handler re-applied the
# event instead of recognising the duplicate, the row would be corrupted and the assertions
# below would fail - which is exactly the regression this guards.
DUP=$(python3 - "$WORKDIR/ready.json" "$USER_ID" <<'PY'
import json, sys
v = json.load(open(sys.argv[1]))
print(json.dumps({
    "videoId": v["id"], "userId": sys.argv[2],
    "hlsManifestUrl": v["playbackUrl"],
    "posterUrl": v["posterUrl"], "spriteSheetUrl": v["thumbnailSpriteUrl"],
    "spriteFrameCount": 0, "spriteColumns": 0,
    "durationSeconds": 999, "width": 1, "height": 1,
    "renditions": [], "processedAt": "2026-01-01T00:00:00Z",
}))
PY
)
CODE=$(rabbit_publish "video.ready" "$DUP")
[ "$CODE" = "200" ] || fail "could not publish the duplicate event (HTTP $CODE)"
sleep 4
BODY=$(auth_curl "$VIDEO_URL/api/v1/videos/$VIDEO_ID")
STATUS=$(printf '%s' "$BODY" | jq_get "['videoStatus']")
DURATION=$(printf '%s' "$BODY" | jq_get "['durationSeconds']")
RENDITIONS=$(printf '%s' "$BODY" | jq_get "[ 'renditions' ].__len__()")
[ "$STATUS" = "READY" ] || fail "duplicate ready event changed status to $STATUS"
[ "$DURATION" != "999" ] || fail "duplicate event overwrote durationSeconds"
[ "$RENDITIONS" = "6" ] || fail "duplicate event replaced the ladder with $RENDITIONS renditions"
pass "ignored: status=READY duration=$DURATION renditions=$RENDITIONS"

step "An undecodable upload fails terminally with a machine-readable reason"
GARBAGE_RESPONSE=$(create_video "garbage bytes")
GARBAGE_ID=$(printf '%s' "$GARBAGE_RESPONSE" | jq_get "['videoId']")
GARBAGE_URL=$(printf '%s' "$GARBAGE_RESPONSE" | jq_get "['uploadUrl']" | to_public)
printf 'this is definitely not a video file' > "$WORKDIR/garbage.mp4"
curl -s -o /dev/null -X PUT "$GARBAGE_URL" -H 'Content-Type: video/mp4' \
    --data-binary "@$WORKDIR/garbage.mp4"
auth_curl -o /dev/null -X POST "$VIDEO_URL/api/v1/videos/$GARBAGE_ID/complete"
DEADLINE=$((SECONDS + 120))
STATUS=PROCESSING
while [ $SECONDS -lt $DEADLINE ]; do
    BODY=$(auth_curl "$VIDEO_URL/api/v1/videos/$GARBAGE_ID")
    STATUS=$(printf '%s' "$BODY" | jq_get "['videoStatus']")
    [ "$STATUS" = "READY" ] || [ "$STATUS" = "FAILED" ] && break
    sleep 3
done
[ "$STATUS" = "FAILED" ] || fail "undecodable upload ended as $STATUS, expected FAILED"
REASON=$(printf '%s' "$BODY" | jq_get ".get('failureReason')")
case "$REASON" in
    SOURCE_CORRUPT|NO_VIDEO_STREAM) pass "FAILED / $REASON" ;;
    *) fail "expected a corrupt-source reason, got '$REASON'" ;;
esac

step "A late video.ready cannot resurrect a FAILED video"
LATE=$(python3 - "$GARBAGE_ID" "$USER_ID" <<'PY'
import json, sys
print(json.dumps({
    "videoId": sys.argv[1], "userId": sys.argv[2],
    "hlsManifestUrl": "http://example.invalid/master.m3u8",
    "posterUrl": None, "spriteSheetUrl": None,
    "spriteFrameCount": 0, "spriteColumns": 0,
    "durationSeconds": 5, "width": 1080, "height": 1920,
    "renditions": [], "processedAt": "2026-01-01T00:00:00Z",
}))
PY
)
rabbit_publish "video.ready" "$LATE" > /dev/null
sleep 4
STATUS=$(auth_curl "$VIDEO_URL/api/v1/videos/$GARBAGE_ID" | jq_get "['videoStatus']")
[ "$STATUS" = "FAILED" ] || fail "a late ready event flipped FAILED to $STATUS"
pass "stays FAILED"

echo
printf '%s========================================%s\n' "$GREEN" "$RESET"
printf '%s  PIPELINE OK   videoId=%s%s\n' "$GREEN" "$RESET" "$VIDEO_ID"
printf '%s========================================%s\n' "$GREEN" "$RESET"
